### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/userStory#1]
## Value statement - a requirement, not a solution
As a user 
I need the possibility to input some basic information in my app 
so that it's possible to generate a new flight plan. 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/197201180-4354a28d-7b25-408b-a88c-5b06da3c888c.png)

## Acceptance criteria
- [ ] (input field for the flight number)
- [ ] (input field for the departure airport)
- [ ] (input field for the arrival  airport)
- [ ] (select box for the departure runaway)
- [ ] (select box for the arrival runaway)
- [ ] (date selection field)
- [ ] (hour selection field)
- [ ] (select box for the Aircraft model selection)
- [ ] (input field for the number of passengers)
- [ ] (button "create flight plan")
- [ ] (button "clear data")

## Tasks
- [ ] (create a input field for the flight number)
- [ ] (create a input field for the departure airport)
- [ ] (create a input field for the arrival  airport)
- [ ] (create a select box for the departure runaway)
- [ ] (create a select box for the arrival runaway)
- [ ] (create a date selection field)
- [ ] (create a hour selection field)
- [ ] (create a select box for the Aircraft model selection)
- [ ] (create a input field for the number of passengers)
- [ ] (create a button "create flight plan")
- [ ] (create a button "clear data")

## Size
(medium)

**Comment by dorosiemers** [comment]
Gute Struktur!

**Comment by mpagels** [comment]
Hey Luiz, good start here. Though, the acceptance criteria could be bit clearer.

For example:
What happens, if the user clicks the (button "create flight plan") or (button "clear data")?
The input fields, what type are they?
Are input fields sometimes mandatory (required) to save the plan?

I recommend doing this user story as a second or third one. You should first create a simple list, where you just display flight plans. Later you can create to add plans.
