### ISSUE TITLE
userStory2

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/userStory#2]
## Value statement - a requirement, not a solution
As a user
I need to be able to revise the generated flight plan 
so that errors or mismatch information can be change.

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/197205958-9d71afe3-bccd-4cdf-8342-3f20134d1a61.png)

## Acceptance criteria
- [ ] text information as a result of the flight plan creation process
- [ ] map with the route plot on it, with the waypoints of the route

## Tasks
- [ ] code the flight plan creation process
- [ ] code a basic map with the route plot on it and with the waypoints of the route

## Size
small

**Comment by mpagels** [comment]
The user story mismatches. You write in the `statement` **so that errors or mismatch information can be change.**

But your `acceptance criteria` is not showing anything of that. I would expect something like, "if I click the edit button, something happens` 

This user story would work, if your `value statement` would state, that you just want to render info data.
