### ISSUE TITLE
userStory3

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/userStory#3]
## Value statement - a requirement, not a solution
As a user
I need to be able to save the flight plan that I have just created 
so that I am able to use it again. 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/197208788-175d1083-d974-447c-814f-37c96cf2e046.png)

## Acceptance criteria
- [ ] button to save the flight plan
- [ ] save a flight plan
- [ ] give a name to the flight plan

## Tasks
- [ ] create a button to save the flight plan
- [ ] code the save function

## Size
small

**Comment by dorosiemers** [comment]
How would you enter the name for your flight plan? 😇

**Comment by AHen-C0de** [comment]
I think it would be good to name the user story after its feature name, so you can recognise it instantly on your canban board. 
Give a bit more details on the save function:
- where is it saved (in a state? localstorage?)
- does the save function redirects to another page, where the saved flights are displayed, as shown in the description?
